<style>
#nette-debug .nette-sessionPanel h1 {
    min-width: 400px;
}

#nette-debug .nette-sessionPanel h2 {
    font: 11pt/1.5 sans-serif;
    margin: 0;
    padding: 2px 8px;
    background: #3484d2;
    color: white;
}

#nette-debug .nette-sessionPanel small {
    font-size: 70%;
}

#nette-debug .nette-sessionPanel .nette-inner {
    width: 700px;
}

#nette-debug .nette-sessionPanel table {
    width: 100%;
    white-space: nowrap;
}

#nette-debug .nette-sessionPanel td.title {
    font-weight: bold;
}

#nette-debug .nette-sessionPanel .remove b {
    line-height: 20px;
    cursor: pointer;
    -webkit-appearance: none;
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-size: 20px;
    font-weight: bold;
    line-height: 20px;
    color: black;
    text-shadow: 0 1px 0 white;
    opacity: 0.2;
    vertical-align: bottom;
    text-decoration: none;
}

#nette-debug .nette-sessionPanel .remove a:hover {
    background: transparent;
    color: #125EAE;
}

#nette-debug .nette-sessionPanel .remove a:hover span {
    text-decoration: underline;
}
</style>

<div class="nette-sessionPanel">
    <h1>Session <small>(Max lifetime: <?php echo $time($sessionMaxTime); ?>)</small></h1>
    <div class="nette-inner">
        <table>
            <thead><tr><th>Name</th><th>Data</th><th>Expires in</th><th></th></tr></thead>
            <tbody>
            <?php foreach ($sections as $section): ?><tr>
                <td class="title" width="10%"><?php echo $esc($section->title); ?></td>
                <td><?php echo $click($section->data); ?></td>
                <td width="5%"><?php echo $esc($section->expiration); ?></td>
                <td width="1%" class="remove"><a href="<?php echo $esc($del($section->title)); ?>"><b>×</b></a></td>
            </tr><?php endforeach; ?>
            </tbody>
        </table>

        <p class="remove"><a href="<?php echo $esc($del()); ?>"><b>×</b> <span>Delete whole session</span></a></p>
    </div>
</div>
